Update chaos-bugbounty-list.json with Schiphol
projectdiscovery/public-bugbounty-programs pull request #290
Opened 2022-01-11 09:43 UTC by risup8682

2022-01-15 11:29 UTC, martinvw commented
Your diff seems to be very big was this intended?

2022-01-17 20:25 UTC, risup8682 commented
I also beautified the JSON file. That's the reason all lines are changed.

2022-01-18 06:22 UTC, ehsandeep requested changes
Please rebase from master without making any format updates.

2022-03-06 10:15 UTC, ehsandeep approved these changes

2022-03-06 10:15 UTC, merged