Adding Brazilian programs from bughunt.com.br
projectdiscovery/public-bugbounty-programs pull request #295
Opened 2022-01-27 05:29 UTC by toguko

Adding Brazilian programs from the Bug Bounty platform bughunt.com.br

2022-02-04 09:40 UTC, martinvw requested changes

2022-02-04 09:40 UTC, martinvw commented on chaos-bugbounty-list.json
> +        "site.tim.com.br"
Please leave out all the subdomains

2022-02-04 09:40 UTC, martinvw commented on chaos-bugbounty-list.json
> +        "https://play.google.com/store/apps/details?id=com.schibsted.bomnegocio.androidApp&hl=pt_BR&showAllReviews=true",
These should not be included, see also: https://github.com/projectdiscovery/public-bugbounty-programs#-notes

2022-02-04 09:40 UTC, martinvw commented on chaos-bugbounty-list.json
> +        "site.tim.com.br",
This one also appears on line 7476, which seems odd

2022-02-04 09:40 UTC, martinvw commented on chaos-bugbounty-list.json
> +        "apigw.olx.com.br/(WIP)",
Please leave out paths, just domains

2022-03-06 09:56 UTC, ehsandeep approved these changes

2022-03-06 09:56 UTC, merged