GitHub Action workflow to detect non accessible program urls
projectdiscovery/public-bugbounty-programs pull request #474
Opened 2023-02-27 12:21 UTC by xm1k3

2023-03-01 07:30 UTC, Mzack9999 requested changes
suggesting minor changes related to naming

2023-03-01 07:30 UTC, Mzack9999 commented on .github/workflows/domains-validation.yml
> +'on':
Shouldn't this work with just `on`?

2023-03-01 07:30 UTC, Mzack9999 commented on .github/workflows/domains-validation.yml
> +  workflow_dispatch: null
I think also here leaving it empty should do the trick

2023-03-01 07:30 UTC, Mzack9999 commented on .github/workflows/domains-validation.yml
> +      - name: null
Let's use more meaningful action names (eg. `checking URL availability`)

2023-03-01 07:30 UTC, Mzack9999 commented on .github/workflows/httpx-check-cron.yaml
> +      - name: null
same as above

2023-03-01 14:11 UTC, Mzack9999 approved these changes

2023-03-04 08:36 UTC, ehsandeep approved these changes

2023-03-04 08:46 UTC, merged