Added Yeswehack scope
projectdiscovery/public-bugbounty-programs pull request #881
Opened 2024-07-30 21:30 UTC by bbacountb

Added Yeswehack scope, with good json syntax

2024-07-31 10:19 UTC, GeorginaReeder commented
Thanks for your contribution @bbacountb !

2024-08-02 07:32 UTC, bbacountb commented
Can this be reviewed?

2024-08-04 21:37 UTC, jdouliez commented
Waiting this PR !!!! :)

2024-08-05 15:04 UTC, dwisiswant0 requested changes

2024-08-05 15:04 UTC, dwisiswant0 commented on chaos-bugbounty-list.json
> +      "name": "Govtech",
```suggestion
      "name": "GovTech",
```

2024-08-05 15:04 UTC, dwisiswant0 commented on chaos-bugbounty-list.json
> +      "name": "Harman International",
```suggestion
      "name": "HARMAN International",
```

2024-08-05 15:04 UTC, dwisiswant0 commented on chaos-bugbounty-list.json
> +      "name": "Spacelift Io",
```suggestion
      "name": "Spacelift.io",
```

2024-08-05 15:04 UTC, dwisiswant0 commented on chaos-bugbounty-list.json
> +      "name": "Vfs",
```suggestion
      "name": "VFS Global",
```

2024-08-08 18:41 UTC, ehsandeep approved these changes
@dwisiswant0 we can address workflow related issues separately - https://github.com/projectdiscovery/public-bugbounty-programs/issues/887

2024-08-08 18:41 UTC, merged